name: Build & Release Electron App

on:
  push:
    tags:
      - 'v*' # Dispara apenas quando criar tags como v1.0.0, v1.0.1, etc.

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write # Permissão para criar o Release e subir o arquivo

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Aqui configuramos para usar o SEU Node.js v24
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependências
        # 'npm ci' é melhor que 'npm install' para servidores de build (mais rápido e fiel)
        run: npm ci

      - name: Build & Publish
        env:
          # O GitHub pega o token das configurações secretas automaticamente aqui
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        # O comando abaixo constrói e publica
        run: npm run build && npx electron-builder --win --publish always